import { z } from "zod";

const createStaffDto = z.object({
  data: z
    .object({
      username: z
        .string()
        .min(3, "Username must be at least 3 characters")
        .trim()
        .toLowerCase()
        .optional(), // Auto-generated by default, optional if user wants custom
      displayName: z.string().trim().optional(),
      email: z.string().email("Invalid email format").trim().toLowerCase().optional(),
      phone: z.string().trim().optional(),
      password: z
        .string()
        .min(6, "Password must be at least 6 characters")
        .optional(),
      roleId: z
        .string()
        .min(1, "Role ID is required"),
    })
    .strict(),
});

const updateStaffDto = z.object({
  data: z
    .object({
      displayName: z.string().trim().optional(),
      email: z.string().email("Invalid email format").trim().toLowerCase().optional(),
      phone: z.string().trim().optional(),
      roleId: z.string().optional(),
      isActive: z.boolean().optional(),
    })
    .strict(),
});

export const StaffDto = {
  create: createStaffDto,
  update: updateStaffDto,
};
